services:
    frontend:
        image: node:22.12
        working_dir: /app
        volumes:
            - ./frontend:/app
        ports:
            - "5173:5173"
        command: sh -c "npm install && npm run dev -- --host"

    backend:
        image: python:3.13
        working_dir: /app
        volumes:
            - ./backend:/app
        ports:
            - "8000:8000"
        command: sh -c "pip install -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8000 --reload"

    db:
        image: postgres:15
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: chatdb
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
