services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "7001:3000"
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment:
            DATABASE_URL: postgres://user:password@db:5432/chatdb
        ports:
            - "7000:8000"
        depends_on:
            - db

    db:
        image: postgres:15
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: chatdb
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
