name: Deploy docker compose

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to server via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                      set -ex
                      cd /srv/chat
                      git pull origin master
                      sudo systemctl restart chat-app.service
